//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    public partial class onea : DbContext
    {
        public onea()
            : base("name=onea")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AlcoholByVolume> AlcoholByVolumes { get; set; }
        public DbSet<BarMenuBeverageInstance> BarMenuBeverageInstances { get; set; }
        public DbSet<BasicUser> BasicUsers { get; set; }
        public DbSet<BasicUserLabel> BasicUserLabels { get; set; }
        public DbSet<Beverage> Beverages { get; set; }
        public DbSet<BeverageAward> BeverageAwards { get; set; }
        public DbSet<BeverageBrand> BeverageBrands { get; set; }
        public DbSet<BeverageProducer> BeverageProducers { get; set; }
        public DbSet<BeverageSubType> BeverageSubTypes { get; set; }
        public DbSet<BeverageSubTypeXRef> BeverageSubTypeXRefs { get; set; }
        public DbSet<BeverageType> BeverageTypes { get; set; }
        public DbSet<BeverageVarietalXRef> BeverageVarietalXRefs { get; set; }
        public DbSet<BlogPost> BlogPosts { get; set; }
        public DbSet<BusinessBeverageCategory> BusinessBeverageCategories { get; set; }
        public DbSet<BusinessBeverageFoodPairing> BusinessBeverageFoodPairings { get; set; }
        public DbSet<BusinessBeverageMenu> BusinessBeverageMenus { get; set; }
        public DbSet<BusinessDrinkSpecial> BusinessDrinkSpecials { get; set; }
        public DbSet<BusinessFoodItem> BusinessFoodItems { get; set; }
        public DbSet<BusinessFoodItemCategory> BusinessFoodItemCategories { get; set; }
        public DbSet<BusinessFoodSpecial> BusinessFoodSpecials { get; set; }
        public DbSet<BusinessHour> BusinessHours { get; set; }
        public DbSet<BusinessUser> BusinessUsers { get; set; }
        public DbSet<BusinessUserBeverageXRef> BusinessUserBeverageXRefs { get; set; }
        public DbSet<BusinessUserRestaurantCategoryXRef> BusinessUserRestaurantCategoryXRefs { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<Follow> Follows { get; set; }
        public DbSet<FoodMenu> FoodMenus { get; set; }
        public DbSet<LearnArticle> LearnArticles { get; set; }
        public DbSet<LearnCategory> LearnCategories { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<ProducerBeverageCategory> ProducerBeverageCategories { get; set; }
        public DbSet<ProducerUser> ProducerUsers { get; set; }
        public DbSet<ProfileCoverPhoto> ProfileCoverPhotoes { get; set; }
        public DbSet<ProfileTheme> ProfileThemes { get; set; }
        public DbSet<Reservation> Reservations { get; set; }
        public DbSet<RestaurantCategory> RestaurantCategories { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<StatsBarMenuView> StatsBarMenuViews { get; set; }
        public DbSet<StatsBlogPostView> StatsBlogPostViews { get; set; }
        public DbSet<StatsFoodMenuView> StatsFoodMenuViews { get; set; }
        public DbSet<StatsProductListView> StatsProductListViews { get; set; }
        public DbSet<StatsProfileView> StatsProfileViews { get; set; }
        public DbSet<StatsStoryView> StatsStoryViews { get; set; }
        public DbSet<TempBusinessRegistrationInfo> TempBusinessRegistrationInfoes { get; set; }
        public DbSet<TempProducerRegistrationClaimedBeverage> TempProducerRegistrationClaimedBeverages { get; set; }
        public DbSet<TempProducerRegistrationInfo> TempProducerRegistrationInfoes { get; set; }
        public DbSet<UserBeverageXRef> UserBeverageXRefs { get; set; }
        public DbSet<UserBusinessXRef> UserBusinessXRefs { get; set; }
        public DbSet<UserEvent> UserEvents { get; set; }
        public DbSet<UserFoodItemXRef> UserFoodItemXRefs { get; set; }
        public DbSet<UserIsAttendingEvent> UserIsAttendingEvents { get; set; }
        public DbSet<UserPhoto> UserPhotoes { get; set; }
        public DbSet<UserPhotoAlbum> UserPhotoAlbums { get; set; }
        public DbSet<UserProducerXRef> UserProducerXRefs { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserVideo> UserVideos { get; set; }
        public DbSet<Varietal> Varietals { get; set; }
        public DbSet<ViticultureRegion> ViticultureRegions { get; set; }
        public DbSet<WebCrawler> WebCrawlers { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<IsUseraBusiness_Result> IsUseraBusiness(int userId)
        {
            //var userIdParameter = userId.HasValue ?
            var userIdParameter = new System.Data.Entity.Core.Objects.ObjectParameter("userId", userId);
                //new System.Data.Entity.Core.Objects.ObjectParameter("userId", typeof(int));

            var test = new List<System.Data.Entity.Core.Objects.ObjectParameter>();
            test.Add(userIdParameter);

            var another = test.ToArray();
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IsUseraBusiness_Result>("IsUseraBusiness", another);
        }
    }
}
