//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarMenuBeverageInstance
    {
        public BarMenuBeverageInstance()
        {
            this.BusinessDrinkSpecials = new HashSet<BusinessDrinkSpecial>();
        }
    
        public int BarMenuBeverageInstanceId { get; set; }
        public int BusinessUserBeverageXRefId { get; set; }
        public int BusinessBeverageCategoryId { get; set; }
        public string Format { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int SortOrder { get; set; }
    
        public virtual BusinessBeverageCategory BusinessBeverageCategory { get; set; }
        public virtual ICollection<BusinessDrinkSpecial> BusinessDrinkSpecials { get; set; }
        public virtual BusinessUserBeverageXRef BusinessUserBeverageXRef { get; set; }
    }
}
