//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicUser
    {
        public int UserId { get; set; }
        public string Email { get; set; }
        public bool IsLegalAge { get; set; }
        public Nullable<int> BasicUserLabelId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string SefUrl { get; set; }
    
        public virtual BasicUserLabel BasicUserLabel { get; set; }
    }
}
