//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicUserLabel
    {
        public BasicUserLabel()
        {
            this.BasicUsers = new HashSet<BasicUser>();
        }
    
        public int BasicUserLabelId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<BasicUser> BasicUsers { get; set; }
    }
}
