//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeverageBrand
    {
        public BeverageBrand()
        {
            this.Beverages = new HashSet<Beverage>();
        }
    
        public int BeverageBrandId { get; set; }
        public Nullable<int> CrawledProducerId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Beverage> Beverages { get; set; }
        public virtual BeverageProducer BeverageProducer { get; set; }
    }
}
