//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beverage
    {
        public Beverage()
        {
            this.BeverageAwards = new HashSet<BeverageAward>();
            this.BeverageSubTypeXRefs = new HashSet<BeverageSubTypeXRef>();
            this.BeverageVarietalXRefs = new HashSet<BeverageVarietalXRef>();
            this.UserBeverageXRefs = new HashSet<UserBeverageXRef>();
        }
    
        public int BeverageId { get; set; }
        public Nullable<int> BeverageTypeId { get; set; }
        public Nullable<int> BeverageBrandId { get; set; }
        public Nullable<int> BeverageProducerId { get; set; }
        public Nullable<int> AlcoholByVolumeId { get; set; }
        public Nullable<int> ProducerBeverageCategoryId { get; set; }
        public Nullable<int> ViticultureRegionId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Name { get; set; }
        public string CrawledName { get; set; }
        public string ImageUrl { get; set; }
        public string CrawledLocation { get; set; }
        public string BeverageBackground { get; set; }
        public string ProducerNotes { get; set; }
        public string TastingNotes { get; set; }
        public Nullable<System.DateTime> HarvestDate { get; set; }
        public Nullable<System.DateTime> BottlingDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<decimal> PhValue { get; set; }
        public Nullable<decimal> TotalAcidValue { get; set; }
        public string Oak { get; set; }
        public string OakAge { get; set; }
        public string ProductionAmount { get; set; }
        public string FoodPairings { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string SefUrl { get; set; }
        public string LargeImageUrl { get; set; }
    
        public virtual AlcoholByVolume AlcoholByVolume { get; set; }
        public virtual BeverageBrand BeverageBrand { get; set; }
        public virtual BeverageProducer BeverageProducer { get; set; }
        public virtual BeverageType BeverageType { get; set; }
        public virtual City City { get; set; }
        public virtual ProducerBeverageCategory ProducerBeverageCategory { get; set; }
        public virtual State State { get; set; }
        public virtual ViticultureRegion ViticultureRegion { get; set; }
        public virtual ICollection<BeverageAward> BeverageAwards { get; set; }
        public virtual ICollection<BeverageSubTypeXRef> BeverageSubTypeXRefs { get; set; }
        public virtual ICollection<BeverageVarietalXRef> BeverageVarietalXRefs { get; set; }
        public virtual ICollection<UserBeverageXRef> UserBeverageXRefs { get; set; }
    }
}
