//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeverageSubType
    {
        public BeverageSubType()
        {
            this.BeverageSubTypeXRefs = new HashSet<BeverageSubTypeXRef>();
        }
    
        public int BeverageSubTypeId { get; set; }
        public int BeverageTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual BeverageType BeverageType { get; set; }
        public virtual ICollection<BeverageSubTypeXRef> BeverageSubTypeXRefs { get; set; }
    }
}
