//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeverageProducer
    {
        public BeverageProducer()
        {
            this.Beverages = new HashSet<Beverage>();
            this.BeverageBrands = new HashSet<BeverageBrand>();
            this.ProducerBeverageCategories = new HashSet<ProducerBeverageCategory>();
        }
    
        public int BeverageProducerId { get; set; }
        public Nullable<int> ProducerUserId { get; set; }
        public string ProducerName { get; set; }
        public string SefUrl { get; set; }
    
        public virtual ICollection<Beverage> Beverages { get; set; }
        public virtual ICollection<BeverageBrand> BeverageBrands { get; set; }
        public virtual ICollection<ProducerBeverageCategory> ProducerBeverageCategories { get; set; }
    }
}
