//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeverageVarietalXRef
    {
        public int BeverageVarietalId { get; set; }
        public int BeverageId { get; set; }
        public int VarietalId { get; set; }
    
        public virtual Beverage Beverage { get; set; }
        public virtual Varietal Varietal { get; set; }
    }
}
