//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessFoodItem
    {
        public BusinessFoodItem()
        {
            this.BusinessBeverageFoodPairings = new HashSet<BusinessBeverageFoodPairing>();
            this.BusinessFoodSpecials = new HashSet<BusinessFoodSpecial>();
            this.UserFoodItemXRefs = new HashSet<UserFoodItemXRef>();
        }
    
        public int BusinessFoodItemId { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int BusinessFoodItemCategoryId { get; set; }
        public decimal Price { get; set; }
        public int SortOrder { get; set; }
        public string LargeImageUrl { get; set; }
    
        public virtual ICollection<BusinessBeverageFoodPairing> BusinessBeverageFoodPairings { get; set; }
        public virtual ICollection<BusinessFoodSpecial> BusinessFoodSpecials { get; set; }
        public virtual ICollection<UserFoodItemXRef> UserFoodItemXRefs { get; set; }
    }
}
