//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessBeverageFoodPairing
    {
        public int BusinessBeverageFoodPairingId { get; set; }
        public int BusinessFoodItemId { get; set; }
        public int BusinessUserBeverageXRefId { get; set; }
        public string Comment { get; set; }
    
        public virtual BusinessFoodItem BusinessFoodItem { get; set; }
        public virtual BusinessUserBeverageXRef BusinessUserBeverageXRef { get; set; }
    }
}
