//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUser
    {
        public BusinessUser()
        {
            this.BusinessBeverageMenus = new HashSet<BusinessBeverageMenu>();
            this.BusinessUserBeverageXRefs = new HashSet<BusinessUserBeverageXRef>();
            this.BusinessUserRestaurantCategoryXRefs = new HashSet<BusinessUserRestaurantCategoryXRef>();
            this.FoodMenus = new HashSet<FoodMenu>();
            this.StatsBarMenuViews = new HashSet<StatsBarMenuView>();
            this.StatsFoodMenuViews = new HashSet<StatsFoodMenuView>();
            this.UserBusinessXRefs = new HashSet<UserBusinessXRef>();
        }
    
        public int UserId { get; set; }
        public string PhoneNumber { get; set; }
        public string Philosophy { get; set; }
        public string Restaurateur { get; set; }
        public string Sommelier { get; set; }
        public string HeadChef { get; set; }
        public string Website { get; set; }
        public string FacebookUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string PhilosophyVideoLink { get; set; }
        public string AboutVideoLink { get; set; }
        public string MapEmbedCode { get; set; }
        public string SefUrl { get; set; }
    
        public virtual ICollection<BusinessBeverageMenu> BusinessBeverageMenus { get; set; }
        public virtual ICollection<BusinessUserBeverageXRef> BusinessUserBeverageXRefs { get; set; }
        public virtual ICollection<BusinessUserRestaurantCategoryXRef> BusinessUserRestaurantCategoryXRefs { get; set; }
        public virtual ICollection<FoodMenu> FoodMenus { get; set; }
        public virtual ICollection<StatsBarMenuView> StatsBarMenuViews { get; set; }
        public virtual ICollection<StatsFoodMenuView> StatsFoodMenuViews { get; set; }
        public virtual ICollection<UserBusinessXRef> UserBusinessXRefs { get; set; }
    }
}
