//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessDrinkSpecial
    {
        public int BusinessDrinkSpecialId { get; set; }
        public int BarMenuBeverageInstanceId { get; set; }
        public string DayOfWeek { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public decimal Price { get; set; }
    
        public virtual BarMenuBeverageInstance BarMenuBeverageInstance { get; set; }
    }
}
