//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearnArticle
    {
        public int LearnArticleId { get; set; }
        public string Title { get; set; }
        public int LearnCategoryId { get; set; }
        public string Intro { get; set; }
        public string Body { get; set; }
        public string IntroImageUrl { get; set; }
        public string MetaDescription { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual LearnCategory LearnCategory { get; set; }
    }
}
