//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearnCategory
    {
        public LearnCategory()
        {
            this.LearnArticles = new HashSet<LearnArticle>();
        }
    
        public int LearnCategoryId { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<LearnArticle> LearnArticles { get; set; }
    }
}
