//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducerUser
    {
        public ProducerUser()
        {
            this.StatsProductListViews = new HashSet<StatsProductListView>();
            this.StatsStoryViews = new HashSet<StatsStoryView>();
            this.UserProducerXRefs = new HashSet<UserProducerXRef>();
        }
    
        public int UserId { get; set; }
        public Nullable<int> ViticultureRegionId { get; set; }
        public string HeadWinemaker { get; set; }
        public string Philosophy { get; set; }
        public string Website { get; set; }
        public string FacebookUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string BlogUrl { get; set; }
        public string PhoneNumber { get; set; }
        public string PhilosophyVideoLink { get; set; }
        public string AboutVideoLink { get; set; }
        public string MapEmbedCode { get; set; }
        public string ProducerCategory { get; set; }
    
        public virtual ViticultureRegion ViticultureRegion { get; set; }
        public virtual ICollection<StatsProductListView> StatsProductListViews { get; set; }
        public virtual ICollection<StatsStoryView> StatsStoryViews { get; set; }
        public virtual ICollection<UserProducerXRef> UserProducerXRefs { get; set; }
    }
}
