//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileTheme
    {
        public ProfileTheme()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int ProfileThemeId { get; set; }
        public string Name { get; set; }
        public string ScreenshotPath { get; set; }
        public string TileColour { get; set; }
        public string BackgroundColour { get; set; }
        public string Texture { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string FooterFontColour { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
