//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileCoverPhoto
    {
        public ProfileCoverPhoto()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int ProfileCoverPhotoId { get; set; }
        public string Path { get; set; }
    
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
