//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantCategory
    {
        public RestaurantCategory()
        {
            this.BusinessUserRestaurantCategoryXRefs = new HashSet<BusinessUserRestaurantCategoryXRef>();
        }
    
        public int RestaurantCategoryId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<BusinessUserRestaurantCategoryXRef> BusinessUserRestaurantCategoryXRefs { get; set; }
    }
}
