//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempProducerRegistrationInfo
    {
        public TempProducerRegistrationInfo()
        {
            this.TempProducerRegistrationClaimedBeverages = new HashSet<TempProducerRegistrationClaimedBeverage>();
        }
    
        public int TempProducerRegistrationInfoId { get; set; }
        public string RegistrationKey { get; set; }
        public string AccountConfirmationToken { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ClaimedBeverageProducerId { get; set; }
    
        public virtual ICollection<TempProducerRegistrationClaimedBeverage> TempProducerRegistrationClaimedBeverages { get; set; }
    }
}
