//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPhotoAlbum
    {
        public UserPhotoAlbum()
        {
            this.UserPhotoes = new HashSet<UserPhoto>();
        }
    
        public int UserPhotoAlbumId { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<UserPhoto> UserPhotoes { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
