//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProducerXRef
    {
        public int UserProducerXRefId { get; set; }
        public int UserId { get; set; }
        public int ProducerUserId { get; set; }
        public bool DoesLike { get; set; }
        public Nullable<System.DateTime> DateLiked { get; set; }
    
        public virtual ProducerUser ProducerUser { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
