//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBusinessXRef
    {
        public int UserBusinessXRefId { get; set; }
        public int UserId { get; set; }
        public int BusinessUserId { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public bool DoesLike { get; set; }
        public Nullable<System.DateTime> DateLiked { get; set; }
        public Nullable<System.DateTime> DateRated { get; set; }
    
        public virtual BusinessUser BusinessUser { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
