//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.BlogPosts = new HashSet<BlogPost>();
            this.BusinessHours = new HashSet<BusinessHour>();
            this.Follows = new HashSet<Follow>();
            this.Follows1 = new HashSet<Follow>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.ProfileThemes = new HashSet<ProfileTheme>();
            this.StatsProfileViews = new HashSet<StatsProfileView>();
            this.UserBeverageXRefs = new HashSet<UserBeverageXRef>();
            this.UserBusinessXRefs = new HashSet<UserBusinessXRef>();
            this.UserEvents = new HashSet<UserEvent>();
            this.UserFoodItemXRefs = new HashSet<UserFoodItemXRef>();
            this.UserIsAttendingEvents = new HashSet<UserIsAttendingEvent>();
            this.UserPhotoAlbums = new HashSet<UserPhotoAlbum>();
            this.UserProducerXRefs = new HashSet<UserProducerXRef>();
            this.UserVideos = new HashSet<UserVideo>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public Nullable<int> MembershipId { get; set; }
        public Nullable<int> ProfileCoverPhotoId { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string ProfilePicturePath { get; set; }
        public string PreviewImagePath { get; set; }
        public string ThumbnailPicturePath { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string PostalCode { get; set; }
        public string Address { get; set; }
        public string About { get; set; }
        public int ProfileThemeId { get; set; }
        public string StripeCustomerId { get; set; }
    
        public virtual ICollection<BlogPost> BlogPosts { get; set; }
        public virtual ICollection<BusinessHour> BusinessHours { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Follow> Follows { get; set; }
        public virtual ICollection<Follow> Follows1 { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual ProfileCoverPhoto ProfileCoverPhoto { get; set; }
        public virtual ICollection<ProfileTheme> ProfileThemes { get; set; }
        public virtual ProfileTheme ProfileTheme { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<StatsProfileView> StatsProfileViews { get; set; }
        public virtual ICollection<UserBeverageXRef> UserBeverageXRefs { get; set; }
        public virtual ICollection<UserBusinessXRef> UserBusinessXRefs { get; set; }
        public virtual ICollection<UserEvent> UserEvents { get; set; }
        public virtual ICollection<UserFoodItemXRef> UserFoodItemXRefs { get; set; }
        public virtual ICollection<UserIsAttendingEvent> UserIsAttendingEvents { get; set; }
        public virtual ICollection<UserPhotoAlbum> UserPhotoAlbums { get; set; }
        public virtual ICollection<UserProducerXRef> UserProducerXRefs { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        public virtual UserProfile UserProfile2 { get; set; }
        public virtual webpages_Membership webpages_Membership { get; set; }
        public virtual ICollection<UserVideo> UserVideos { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
