//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPhoto
    {
        public int UserPhotoId { get; set; }
        public string Title { get; set; }
        public string Caption { get; set; }
        public string ImageUrl { get; set; }
        public int UserPhotoAlbumId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual UserPhotoAlbum UserPhotoAlbum { get; set; }
    }
}
