//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViticultureRegion
    {
        public ViticultureRegion()
        {
            this.Beverages = new HashSet<Beverage>();
            this.ProducerUsers = new HashSet<ProducerUser>();
            this.ViticultureRegion1 = new HashSet<ViticultureRegion>();
        }
    
        public int ViticultureRegionId { get; set; }
        public Nullable<int> ParentViticultureRegionId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Beverage> Beverages { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<ProducerUser> ProducerUsers { get; set; }
        public virtual ICollection<ViticultureRegion> ViticultureRegion1 { get; set; }
        public virtual ViticultureRegion ViticultureRegion2 { get; set; }
    }
}
