//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1aMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebCrawler
    {
        public int WebCrawlerId { get; set; }
        public string Name { get; set; }
        public string LastRunStatus { get; set; }
        public Nullable<System.DateTime> LastRunTime { get; set; }
        public bool IsRunning { get; set; }
    }
}
